import funDownloadPopularityByDate from "./back/fun/download_popularity_by_date";
import funGetPopularityByDate from "./back/fun/get_popularity_by_date";
import ViewAddRatePaslon from "./back/view/view_add_rate";
import ViewAdminPopularity from "./back/view/view_admin_popularity";
import ViewAdminPopularityNew from "./back/view/view_admin_popularity_new";
import ViewCopyPopularity from "./back/view/view_copy_popularity";
import ViewUploadPopularity from "./back/view/view_upload_popularity";
import funGetChartRateNew from "./front/fun/get_chart_rate_new";
import funGetOnePopularityFront from "./front/fun/get_one_popularity_by_paslon";
import funGetPopularityNew from "./front/fun/get_one_popularity_new";
import funGetPopularityFront from "./front/fun/get_popularity_front";
import funGetRateFront from "./front/fun/get_rate";
import ViewNationalPopularityMetric from "./front/view/view_national_popularity_metric";

export { ViewNationalPopularityMetric }
export { ViewAdminPopularity }
export { funGetPopularityByDate }
export { funDownloadPopularityByDate }
export { ViewUploadPopularity }
export { ViewCopyPopularity }
export { funGetRateFront }
export { funGetOnePopularityFront }
export { funGetPopularityFront }
export { funGetPopularityNew }
export { ViewAdminPopularityNew }
export { ViewAddRatePaslon }
export { funGetChartRateNew }